### ISSUE TITLE
Detail Conversation and Upload of JSON Steps

### ISSUE THREAD

**Issue by sharpstef** [IBM-Bluemix/insurance-bot#104]

**Comment by l2fprod** [comment]
to update the dev and prod deployments under our org/space:
- delete the existing workspace (Ana or Ana Prod) under the conversation service in this workspace
- go to the toolchain, locate the bot(dev) or bot(prod) pipeline.
  - edit the settings of DEPLOY stage
  - change the value of the CONVERSATION_WORKSPACE environment variable to the new workspace ID
- save
- run the Deploy stage

**Comment by l2fprod** [comment]
@slkaczma 

Details added to insurance-bot README https://github.com/IBM-Bluemix/insurance-bot#-importing-the-conversation-workspace-into-your-watson-conversation-service and linked from the toolchain. Should have all we need to deploy the conversation. Closing this one. Reopen if there is something missing.
