### ISSUE TITLE
Add dashboard to dev pipeline

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/insurance-bot#106]

**Comment by l2fprod** [comment]
@colbycheeze @rvennam 

what are the steps to build the app?

npm install?
something else?

what are the steps to run the app?
npm start?

**Comment by colbycheeze** [comment]
Sure I can add that.
For now it's just `cf push` and the defaults for the buildpack take care of everything by doing:

```
npm install
npm start
```

**Comment by l2fprod** [comment]
@colbycheeze 

with `npm install` and `npm start`, I get a 404 "Not found" (NODE_ENV is set to production in the manifest.mf).

So in the BUILD step of the pipeline, I run `npm deploy:prod` to build the webpack in dist. Then in the DEPLOY step, just `cf push`. It is live: https://dev-cloudco-insurance-dashboard.mybluemix.net/
