### ISSUE TITLE
Add a database and link it to app.js

### ISSUE THREAD

**Issue by antonmc** [IBM-Bluemix/insurance-bot#11]

**Comment by antonmc** [comment]
My preference for this remains Mongo, but I accept the decision to work with Cloudant. The important thing is to establish this as soon as possible.

**Comment by VidyasagarMSC** [comment]
I have created a Cloudant DB called "insurance" and added the insurance.JSON created earlier. Working on the app.js linking now.

**Comment by VidyasagarMSC** [comment]
Insurance cloudant DB is created and JSON document with sample insurance data is created | NodeJS app (app.js) is linked to cloudant DB. 

The updated code is sitting under this repo. Pls. verify. Once we are good, will make a pull request to merge with the main branch.
https://github.com/VidyasagarMSC/insurance-bot
