### ISSUE TITLE
Add link to main github repo to banner at top

### ISSUE THREAD

**Issue by uwefassnacht** [IBM-Bluemix/insurance-bot#135]
Similar to this example: https://text-bot.mybluemix.net

Link to main repo of the architecture: https://github.com/IBM-Bluemix/cloudco-insurance

**Comment by kingtraceyj** [comment]
updated designs using the github icon in the upper right hand part of the header.

@uwefassnacht @Austinauth is this apparent enough?

![image](https://cloud.githubusercontent.com/assets/20582179/19361200/4c08739a-9147-11e6-86bb-e2c176e614c1.png)
