### ISSUE TITLE
final touches on branding

### ISSUE THREAD

**Issue by rvennam** [IBM-Bluemix/insurance-bot#136]
Feedback from @kingtraceyj 
- [x] Add github icon https://ibm.box.com/s/xw7x1gsiimqdrc1lm7xwboj3rjcpj7u2
- [x] the insurance icon can shrink a little— height: 26px maybe?
- [x] the header text (cloud insurance co & about & login) should all be the same — 14px
- [ ] also center the icons and buttons in the 4 cards. there seems to be a bit more padding on the bottom than top.
- [x] link colors in the footer can be #5586D6

**Comment by rvennam** [comment]
![image](https://cloud.githubusercontent.com/assets/5502967/19324830/159fdd2a-9089-11e6-9409-3fc1ad9e549b.png)

**Comment by sharpstef** [comment]
Grey out the icons that aren't in use as well and then do a switch when we get active content? That way all the focus immediately goes to health no matter what the platform.

**Comment by sharpstef** [comment]
Are we addressing the elephant of the grey wash on the chat page? I can fix it, but didn't know if we wanted all grey or okay with white chat box?
