### ISSUE TITLE
Remaining Fixes and Bugs for WoW Demo

### ISSUE THREAD

**Issue by Austinauth** [IBM-Bluemix/insurance-bot#143]
List of fixes and bugs that need to be addressed for WoW. List items taken from a visual audit conducted this morning with @colbycheeze and @rvennam.

@kingtraceyj's sketch file: https://ibm.ent.box.com/file/98329167592
## Web App - Health Page

http://dev-cloudco.mybluemix.net/health
- [x] Layout Sizing Ratios
- [x] Tab Left Alignment and Border Bottom
- [x] Category Accordion Module Padding & Text Spacing
- [x] Category Accordion _Close Benefit Copy_
- [x] Correct Color Audit + Variable Creation
- [x] [Export SVGs Icons](https://ibm.ent.box.com/folder/11773537715) (@austinauth)
- [x] Update Page with Correct Icons
- [x] All Caps Headers Need `letter-spacing: 1px`
- [x] Chat Module Missing Name/Time Labels
- [x] Chat Dialog Box Carrot

## Admin Console

https://dev-cloudco-insurance-dashboard.mybluemix.net/
- [x] Warning Notification if Anna Isn't Able to Respond
- [x] Temporarily Remove Smiley Icons From Chat List Until We Can Indicate Sentiment  
- [x] Delete Conversation Needs to Update Graph

**Comment by rvennam** [comment]
Moving unfinished tasks to another issues.

https://github.com/IBM-Bluemix/insurance-bot/issues/150
https://github.com/IBM-Bluemix/insurance-bot-dashboard/issues/35
