### ISSUE TITLE
Use Cloudant as an alternative to MongoDB

### ISSUE THREAD

**Issue by uwefassnacht** [IBM-Bluemix/insurance-bot#15]
Integrate Cloudant as well as MongoDB to:
- show off an alternative NoSQL technology
- demonstrate the ease of replacing a service within a microservice architecture (would make a nice demo point in itself)

**Comment by antonmc** [comment]
Or vice versa if we begin with Cloudant

**Comment by l2fprod** [comment]
@uwefassnacht @antonmc
Compose for MongoDB has no free tier or plan today.
Cloudant has the free Lite plan

the cloudco-insurance should use Cloudant as the default to allow users to deploy using their free tier.

**Comment by l2fprod** [comment]
work started here https://github.com/IBM-Bluemix/insurance-bot/tree/cloudant
