### ISSUE TITLE
Include way to give feedback directly in the app

### ISSUE THREAD

**Issue by uwefassnacht** [IBM-Bluemix/insurance-bot#16]
Include some sort of feedback mechanism directly in the app.

**Comment by Twanawebtech** [comment]
I am taken this task on. Will add feedback form to the website to create issues on GitHub directly.

**Comment by antonmc** [comment]
We need to review the feedback approach.

1] The insurance bot app seems to have a whole other Go app embedded in the same repo. I want to keep the insurance code focused and simple. This other app needs to exist in it's own repo.
2] If we do indeed need a whole other app for feedback - then it should be a microservice that can easily be used by multiple apps. Please work on making a feedback microservice that can take a github repo as a parameter when a project wants to make use of it
3] This feedback project used jquery and bootstrap that conflicted with the insurance site javascript and style. I don't want to depend on those libraries for the insurance project.

With my recent changes, the feedback mechanism is not working anymore. I'm sorry that I had to disconnect it. 

Can this feedback approach not be done in a simple way using the node application that we already have? It should just be a form - post - and route handled by app.js talking to github?
