### ISSUE TITLE
unable to locate vcap local json 

### ISSUE THREAD

**Issue by sourabhks** [IBM-Bluemix/insurance-bot#160]
I am getting error as { [Error: Cannot find module './vcap-local.json'] code: 'MODULE_NOT_FOUND' }
although i have kept vcap-local.json in same path as of app.js and bot.js.
Please help to fix the issue

**Comment by rvennam** [comment]
Can you provide a screenshot of your file structure and the contents of vcap-local.json

**Comment by sourabhks** [comment]
![app vcap call](https://cloud.githubusercontent.com/assets/23342782/21576245/bec2323c-cf4e-11e6-828a-02a4347f0df8.jpg)
![bot vcap call](https://cloud.githubusercontent.com/assets/23342782/21576246/bee5e8ee-cf4e-11e6-9de8-22c12e7e6a37.jpg)
![errors](https://cloud.githubusercontent.com/assets/23342782/21576247/bf0862fc-cf4e-11e6-976b-e0180b3fc4c8.jpg)
![file structure](https://cloud.githubusercontent.com/assets/23342782/21576248/bf1244c0-cf4e-11e6-8c77-ef5aab016d1d.jpg)
![vcap content](https://cloud.githubusercontent.com/assets/23342782/21576249/bf1322e6-cf4e-11e6-8924-e17ec7e383a6.jpg)


Please find the attached screenshot as requested and help to fix the issue. Thanks for your prompt reply

**Comment by l2fprod** [comment]
@sourabhks the vcap-local.json is only needed when you run the app locally. The error message is misleading as when running within Bluemix, the credentials for the database and the Watson service are retrieved from the VCAP_SERVICES automatically.

We should avoid trying to load a vcap-local.json when running in Bluemix or improve the error message.

**Comment by sourabhks** [comment]
Thanks fredrick for your prompt reply. I have one more query.
I did some changes in your code and removed the benefit and claims details.
So i ended up removing all their functions from app.js, ana.js, cloudco.js and the corresponding html.
I now made up a new function replacing the getbenefit function which called userMessage to display the first conversation message on chatbot. 
I am now getting the chat response of chatbot in console.log with all intents, entities and conversation but I am not getting this on the chatbot. Instead I am getting error "I ran into error, could you please try again"

Please help to fix this issue if possible.

**Comment by l2fprod** [comment]
fixed the error message - it will only be shown if something is wrong with the vcap-local.json when it exists.

btw the screenshots you posted expose your credentials - you may want to remove them.

As per your issue, you likely removed something that was needed. Look at the console of the web browser, it should show a bit more information, something like "Server error for Conversation. Return status of....".

If that does not help debug your issue, I suggest you start over cloning the cloudco insurance with the toolchain https://github.com/IBM-Bluemix/insurance-toolchain then removing code step by step, ensuring the app still works after each step.
