### ISSUE TITLE
Chat with Ana throwing URL workspaceid parameter is not a valid GUID error

### ISSUE THREAD

**Issue by VidyasagarMSC** [IBM-Bluemix/insurance-bot#161]
While testing insurance-bot-android, facing this error while chatting with Ana. Able to reproduce the same on iOS client. 

"error":"URL workspaceid parameter is not a valid GUID."

**Comment by l2fprod** [comment]
The conversation workspace id was not set in the live pipeline for cloudco and dev-cloudco following the new pipeline updates.
