### ISSUE TITLE
Chatbot missing conversation related to jump statement

### ISSUE THREAD

**Issue by sourabhks** [IBM-Bluemix/insurance-bot#162]
Whenever there is a follow up conversation with a Jump statement. The chatbot is missing that conversation. Please look into it and let me know the related changes.
![ana conversation](https://cloud.githubusercontent.com/assets/23342782/21763446/f84ac230-d683-11e6-85f6-02c6f0bf41c3.jpg)
![watson trained conversation](https://cloud.githubusercontent.com/assets/23342782/21763448/f86e4732-d683-11e6-8025-9e9db2b9f4d8.jpg)

**Comment by l2fprod** [comment]
can you describe what are the steps to reproduce the issue and what is the behavior you expect?

**Comment by sourabhks** [comment]
The steps to reproduce the issues are as follows:
1) type  "Make a Claim"
2) it will ask for what have you done, Then type "tooth filling"
3) you will notice a difference in output behavior between watson conversation output as in image2
   and ana conversation output as in image1.

The normal behavior should be that the watson trained conversation should be reflected by ana chatbot but it is not so. What I noticed was that whenever there is a Jump statement, The ana chatbot is missing it. 
Kindly look into it and let me know how to resolve it. Thanks

**Comment by sourabhks** [comment]
I have figured the reason for difference. The bot.js is coded to display only the first response message. I changed that line to print entire response.output.text array and it's working fine now.
Thanks for your prompt reply

Can you please tell me how to view the  dashboard logged conversation records, TIA

**Comment by l2fprod** [comment]
Going to close that one.

The dashboard is a separate app (https://github.com/IBM-Bluemix/insurance-bot-dashboard) that is deployed by the toolchain if you used that (https://github.com/IBM-Bluemix/insurance-toolchain).
