### ISSUE TITLE
Bot won't accept valid dates for claims

### ISSUE THREAD

**Issue by IanKHall** [IBM-Bluemix/insurance-bot#166]
"Sorry Marty McFly we don't accept dates in the future..." I get this answer when giving valid dates in the past for a claim.

**Comment by l2fprod** [comment]
@IanKHall 

how did you deploy the example?
did you use the toolchain https://github.com/IBM-Bluemix/insurance-toolchain?
or is it with a deployed version?
what are the steps to reproduce the issue?

**Comment by IanKHall** [comment]
I am working with bots at the following URLs:
https://bcbsma-insurance-bot.mybluemix.net/
 http://cloudco.mybluemix.net
Am using the Chrome browser.
Ian Hall
Senior Certified Software Client Architect
Certified Cloud Solution Advisor
IBM Public Sector & Healthcare Industry
ikhall@us.ibm.com
1-917-405-5569
Follow me on Twitter: @IanKHall

**Comment by l2fprod** [comment]
to reproduce:

you:  file a claim
Ana | 8:23 am Let me take care of that paperwork for you. What did you have done?
you:  tooth repair
Ana | 8:23 am Got it. Now what was the date of your appointment?                                                              you: 2017-01-23
Ana | 8:23 am  Sorry, Marty McFly, you can't make a claim in the future. Please try the
 date again.

**Comment by IanKHall** [comment]
Yes that is correct. But my colleague Sridhar Shetty fixed it for the
instance of the chatbot we will be demonstrating to a client tomorrow.
Using Chrome and the bot available at
https://bcbsma-insurance-bot.mybluemix.net/login
I get the following dialog now:
                                                               an | 1:26 pm
            file a claim

Ana | 1:26 pm
 Let me take care of that paperwork for you. What did you have done?

                                                              Ian | 1:27 pm
            teeth cleaning

Ana | 1:27 pm
 Got it. Now what was the date of your appointment?

                                                              Ian | 1:27 pm
            2017-01-23

Ana | 1:27 pm
 I have a date of 2017-01-23. Is that right?

                                                              Ian | 1:27 pm
            yes

Ana | 1:27 pm
 Fantastic. What is the name of the provider or physician you went to?

Thank you!
Ian Hall
Senior Certified Software Client Architect
Certified Cloud Solution Advisor
IBM Public Sector & Healthcare Industry
ikhall@us.ibm.com
1-917-405-5569
Follow me on Twitter: @IanKHall
