### ISSUE TITLE
Problem filing a claim

### ISSUE THREAD

**Issue by IanKHall** [IBM-Bluemix/insurance-bot#167]
I get an error filing a claim, with no explanation of what the error is. But the claim does appear in the Claims list. ???

**Comment by l2fprod** [comment]
@IanKHall 

can you describe to reproduce the issue?
anything in the browser console or in the app logs?

**Comment by IanKHall** [comment]
Interacting with the bot at  http://cloudco.mybluemix.net/health    :
Ana | 8:23 am
 What information do you need about tooth repair?

                                                              Ian | 8:23 am
            file a claim

Ana | 8:23 am
 Let me take care of that paperwork for you. What did you have done?

                                                              Ian | 8:23 am
            tooth repair

Ana | 8:23 am
 Got it. Now what was the date of your appointment?

                                                              Ian | 8:23 am
            2017-01-23

Ana | 8:23 am
 Sorry, Marty McFly, you can't make a claim in the future. Please try the
 date again.
Ian Hall
Senior Certified Software Client Architect
Certified Cloud Solution Advisor
IBM Public Sector & Healthcare Industry
ikhall@us.ibm.com
1-917-405-5569
Follow me on Twitter: @IanKHall
