### ISSUE TITLE
Chatbot is throwing message "I ran into an error. Could you please try again." on application start

### ISSUE THREAD

**Issue by amitsaini** [IBM-Bluemix/insurance-bot#172]
I have followed all the steps and setup the insurance  chatbot.I deployed on bluemix and all services, db, tradeoff analytics shown good health. But on application start Chatbot is throwing message "I ran into an error. Could you please try again." 
I have looked in logs also, only message I found is : Error in sending message: { [Error: Resource not found] code: undefined, error: 'Resource not found' }.

I know it looks very generic. But till now I have acquired very little debugging or fixing capability.

So please help me?

Thanks
Amit

**Comment by l2fprod** [comment]
@amitsaini 

Have you set the WORKSPACE_ID in the DEPLOY stage of the insurance-bot pipeline?

Can you restart the insurance-bot app, repeat the steps and attach the insurance-bot app log files to this issue?

**Comment by amitsaini** [comment]
Hi Fred,
For better clarity and debugging I host all the apps locally and end with same error.
Here is the screenshot and error message in text file
[Error.txt](https://github.com/IBM-Bluemix/insurance-bot/files/829835/Error.txt)
![error-ss](https://cloud.githubusercontent.com/assets/3437272/23736910/69e78b62-04b5-11e7-82e3-d3fb514795cd.png)


.

**Comment by l2fprod** [comment]
@amitsaini it would be good if you could copy the full output including the app startup. Did you specify the WORKSPACE_ID?

**Comment by l2fprod** [comment]
please reopen with more information.
