### ISSUE TITLE
Use new API to create workspace (vs. loading it manually from a file)

### ISSUE THREAD

**Issue by uwefassnacht** [IBM-Bluemix/insurance-bot#174]
The conversation service now has an API to create a workspace and load content into it. 

That allows us to get rid of the manual step of uploading ana.json : 

https://www.ibm.com/watson/developercloud/conversation/api/v1/#create_workspace

**Comment by l2fprod** [comment]
on bot startup:

- if CONVERSATION_WORKSPACE environment variable is set, use this one. This will allow us to have separate workspace for our "dev" and "prod" environment within the same conversation service instance

- if CONVERSATION_WORKSPACE is not set
  - query the conversation service for a workspace named "Ana"
  - if the workspace exist, use it
  - if the workspace does not exist, import Ana.json
