### ISSUE TITLE
Remove Tradeoff analytics from demo

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/insurance-bot#179]
https://www.ibm.com/blogs/bluemix/2017/04/deprecation-tradeoff-analytics/

**Comment by uwefassnacht** [comment]
Bluemix [toolchain](https://console.ng.bluemix.net/devops/toolchains/4811990e-3862-415d-b259-9b453e97247a "insurance-toolchain-eu"): [Delivery Pipeline](https://console.ng.bluemix.net/devops/pipelines/3f0dbc0e-31dc-44d8-8095-2194e53de0f4 "bot (master)") deployed [insurance-bot](https://github.com/IBM-Bluemix/insurance-bot/releases/tag/deploy-DEPLOY-20170419-120046 "deploy-DEPLOY-20170419-120046") to [DEPLOY](https://console.eu-gb.bluemix.net/apps/b45651d9-35eb-4da2-b598-86bba635d077 "There was a problem retrieving the space name"), including commit e05784d3d4ee5e9bd9ad7c60d7a1bd2a747570ea

**Comment by uwefassnacht** [comment]
Bluemix [toolchain](https://console.ng.bluemix.net/devops/toolchains/4811990e-3862-415d-b259-9b453e97247a "insurance-toolchain-eu"): [Delivery Pipeline](https://console.ng.bluemix.net/devops/pipelines/178cb417-26a1-4fb6-9d3a-80cbc1c76462 "catalog (master)") deployed [insurance-catalog](https://github.com/IBM-Bluemix/insurance-catalog/releases/tag/deploy-DEPLOY-20170419-120059 "deploy-DEPLOY-20170419-120059") to [DEPLOY](https://console.eu-gb.bluemix.net/apps/2eee6511-4343-4d61-b4e5-581db4db589d "There was a problem retrieving the space name"), including commit insurance-catalog@5d629874a86fa08f5975d2511b13a0075bb7533f

**Comment by uwefassnacht** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/4811990e-3862-415d-b259-9b453e97247a "insurance-toolchain-eu"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/178cb417-26a1-4fb6-9d3a-80cbc1c76462 "catalog (master)") deployed [insurance-catalog](https://github.com/IBM-Bluemix/insurance-catalog/releases/tag/deploy-ibm-yp-eu-gb-uwe.fassnacht-de.ibm.com-cloudco-20171208-094815 "deploy-ibm-yp-eu-gb-uwe.fassnacht-de.ibm.com-cloudco-20171208-094815") to [cloudco](https://console.bluemix.net/apps/888ea00c-335d-45c1-97c5-f60c90f39ff5?env_id=ibm:yp:eu-gb "ibm:yp:eu-gb:uwe.fassnacht@de.ibm.com:cloudco"), including commit IBM-Bluemix/insurance-catalog@5d629874a86fa08f5975d2511b13a0075bb7533f

**Comment by uwefassnacht** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/4811990e-3862-415d-b259-9b453e97247a "insurance-toolchain-eu"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/3f0dbc0e-31dc-44d8-8095-2194e53de0f4 "bot (master)") deployed [insurance-bot](https://github.com/IBM-Bluemix/insurance-bot/releases/tag/deploy-ibm-yp-eu-gb-uwe.fassnacht-de.ibm.com-cloudco-20171208-140750 "deploy-ibm-yp-eu-gb-uwe.fassnacht-de.ibm.com-cloudco-20171208-140750") to [cloudco](https://console.bluemix.net/apps/9329ca18-f221-4d54-8ab3-cfa480b1bf03?env_id=ibm:yp:eu-gb "ibm:yp:eu-gb:uwe.fassnacht@de.ibm.com:cloudco"), including commit e05784d3d4ee5e9bd9ad7c60d7a1bd2a747570ea
