### ISSUE TITLE
Create Policy page for a client

### ISSUE THREAD

**Issue by antonmc** [IBM-Bluemix/insurance-bot#18]
When a client successfully logs in they will be able to see their policy or policies. For example a health policy that lists entitlements for vision, dental, medical services - along with the status of those services ( how much the entitlement is, when the entitlement is valid for, claims against it, claims rejected ).

**Comment by Twanawebtech** [comment]
I will create that.

**Comment by VidyasagarMSC** [comment]
@Twanawebtech @antonmc Which templating engine (Jade,EJS,Handlebars etc.,) are we planning to use here?

**Comment by antonmc** [comment]
I'd prefer we just used HTML5, CSS3 and JS - no template engine - but discuss. We won't have very many pages.

**Comment by antonmc** [comment]
With restful data ( that we can reuse in the messaging frameworks eventually )

**Comment by Twanawebtech** [comment]
@antonmc @VidyasagarMSC I am using EJS if that's ok with you guys, I have used both EJS and Jade in past and I am bigger fan of EJS because of their simplicity, we can imbed nicely all the HTML5 into EJS, it will just structure the HTML code better.

**Comment by Twanawebtech** [comment]
This is done. http://cloudco.mybluemix.net/ and checkout the Develop Branch on GitHub
