### ISSUE TITLE
How to Deploy?

### ISSUE THREAD

**Issue by shubhamverma27** [IBM-Bluemix/insurance-bot#183]
Hey,
I am new to Bluemix and wanted to try out this chatbot.
How do I deploy it?
I am not able to understand the steps given in readme!

**Comment by data-henrik** [comment]
we updated the steps

**Comment by VidyasagarMSC** [comment]
@shubhamverma27  You can use the toolchain - https://github.com/IBM-Cloud/insurance-toolchain
