### ISSUE TITLE
Responsive landing page 

### ISSUE THREAD

**Issue by antonmc** [IBM-Bluemix/insurance-bot#36]
The landing page should look good on a phone too.

**Comment by Twanawebtech** [comment]
@antonmc are you handling this? If you not working on this then I will take this on.

I have done many responsive sites and UI is one of my strong points, so with few hours I can restyle the full CloudCo app with a more active live design while been responsive and making sure it will displays well in all screens.

Also I have a collection of responsive work in which I can reuse. 
let me know your thoughts, I would happily take this task on if you want.

**Comment by antonmc** [comment]
I'll push some code for this tomorrow. I have them working locally. We will need responsive, and pretty pages for the policy info and claim form though - it's kind of hard to figure out as it is.
