### ISSUE TITLE
Move CloudCo to different space on Bluemix

### ISSUE THREAD

**Issue by Twanawebtech** [IBM-Bluemix/insurance-bot#54]
Move cloudco app on Bluemix to cloudco-prod space. There I also deployed the API application for for feeding issues back to GitHub.

**Comment by l2fprod** [comment]
@Twanawebtech @antonmc 

we now have a prod cloudco in its own space. I changed the route of the cloudco in the demos space. I'm not touching those apps. I don't know if you want to capture or backup anything there. Back at you two :)

**Comment by l2fprod** [comment]
nothing more to do here - feedback app is no longer part of the site.
