### ISSUE TITLE
Create a slack channel for Cloud Co insurance.

### ISSUE THREAD

**Issue by antonmc** [IBM-Bluemix/insurance-bot#6]

**Comment by aspleenic** [comment]
Created the channel under the Bluemix slack

**Comment by antonmc** [comment]
ah - I should have been a lot clearer - I meant a public one - I guess a slack account for cloudco so we could use it with public messaging later, and have an easy way of onboarding from our website

**Comment by aspleenic** [comment]
Ahh - gotcha - in that case: https://cloud-co-insurance.slack.com
