### ISSUE TITLE
Make a new 'about' page

### ISSUE THREAD

**Issue by antonmc** [IBM-Bluemix/insurance-bot#66]
The 'about' link is broken. Want to make a new page that talks about the four tile projects and the services behind them, links to Watson and possibly articles about chat bots.

Home - I see this as an opportunity for a weather related demo - maybe taking your location and showing the weather your home has been subjected to in the past year. Maybe working with some open data.

Health - benefit bot - chatting to claim on health benefits

Auto - I'd really like to pull in some IoT with this - a simulation of road trips etc

Travel - Trade off analytics on choosing a policy

**Comment by l2fprod** [comment]
about points to the project wiki where info will be added along the way about the different pieces of the app - together with the links to blog post, etc.
