### ISSUE TITLE
feedback after meeting 24/09

### ISSUE THREAD

**Issue by Twanawebtech** [IBM-Bluemix/insurance-bot#79]
**Feedback**
1) ReadMe is need work, you can’t follow what is done as to now
2) I can’t run the app if clone it 
3) No info on what is done on the ChatBot part model 
4) Design need to be responsive

**Good Blogs can be made out of that**
1) Migration of Node, Mongo and passport to Bluemix 
2) Show off ChatBot with using Mongo working.
3) How the model is done for the conversation API

**Comment by l2fprod** [comment]
this has been covered for WoW. Individual blogs to be looked at in their own tasks
