### ISSUE TITLE
Add Wiki to repo

### ISSUE THREAD

**Issue by uwefassnacht** [IBM-Bluemix/insurance-bot#81]
- [ ] Links to more info and collateral (videos, demo script, service docs, ....)

Example here: https://github.com/IBM-Bluemix/logistics-wizard/wiki

**Comment by l2fprod** [comment]
@uwefassnacht hold to that until "cloudco-insurance" repo is created in #101

**Comment by l2fprod** [comment]
@uwefassnacht https://github.com/IBM-Bluemix/cloudco-insurance

**Comment by l2fprod** [comment]
added overall description of the app and how conversation/toneanalyzer are used in the wiki.
wiki linked from the app home page and from the main github page
