### ISSUE TITLE
Add a mobile app component to the architecture

### ISSUE THREAD

**Issue by uwefassnacht** [IBM-Bluemix/insurance-bot#83]
Allow a user to log in and chat with the insurance-bot via a mobile app.

The mobile app will be written in Swift 3.0 and run on iOS.

**Comment by Austinauth** [comment]
Following up on our meeting this afternoon, also expanding on @uwefassnacht's above post.

## Customer View - Design Requirements
- User login page
- Landing page
  - Categories
  - Claim History (?)
- Chat bot screen

Questions:
- At what stage does the user log in?
- Does the user select a category (health, home, auto, travel)? Or go straight to invoking the chat?

**Comment by uwefassnacht** [comment]
> At what stage does the user log in?

Early on ... even right away? Login with a fingerprint would be very cool.

> Does the user select a category (health, home, auto, travel)? Or go straight to invoking the chat?

Selects a category, but only the health category is actually active (at least for this Milestone)
