### ISSUE TITLE
Update README.md and add Wiki to repo

### ISSUE THREAD

**Issue by uwefassnacht** [IBM-Bluemix/insurance-bot#84]
Overhaul of README.md additon of a Wiki (with more information about this architecture)

**Comment by l2fprod** [comment]
@uwefassnacht 
like for Logistics Wizard, let's have a new top-level project "cloudco-insurance". Then we will link insurance-bot (the webui+bot), insurance-catalog, insurance-orders, and insurance-toolchain from this project.

We should also rename the repos with cloudco-insurance prefix

(Tracked in https://github.com/IBM-Bluemix/insurance-bot/issues/84#issuecomment-251118859)
