### ISSUE TITLE
Adminstrator dashboard with Watson Tone Analysis

### ISSUE THREAD

**Issue by uwefassnacht** [IBM-Bluemix/insurance-bot#85]
Add an "administrator" view to insurance-bot. This will allow:
- an admin to monitor various users chats
- Watson tone analyzer to constantly evaluate tone of the chats
- generation of alerts, once thresholds are breached (e.g. tone becomes very angry or happy)

**Comment by Austinauth** [comment]
Following up on our meeting this afternoon, also expanding on @uwefassnacht's above post. 

## Insurance Admin View - Design Requirements

**Admin Chat UI:**
- Monitoring user chat logs
- Surfacing user sentiment analysis
- Sentiment alerts (notification when a sentiment threshold is breached)
- Watson alert (notification to update Watson training)
- Site layout & demo placeholder analytics
