### ISSUE TITLE
CloudCo branding for mobile app, main site and admin dashboard

### ISSUE THREAD

**Issue by uwefassnacht** [IBM-Bluemix/insurance-bot#87]
Cloud Co branding for:
- admin dashboard
- mobile app
- main site site

Make it feel like a real insurance site:
- maybe adding a photo of a nuclear family flying a kite on a gorgeous field?
- contrast that will look well on a projector an in darkened auditorium

**Comment by kingtraceyj** [comment]
@colbycheeze fonts and colors so far

![image](https://cloud.githubusercontent.com/assets/20582179/19157070/b317658a-8ba9-11e6-806a-97f9088a9a02.png)

**Comment by kingtraceyj** [comment]
![image](https://cloud.githubusercontent.com/assets/20582179/19157070/b317658a-8ba9-11e6-806a-97f9088a9a02.png)

**Comment by kingtraceyj** [comment]
@colbycheeze 
yellow instead of orange for the warnings now

![image](https://cloud.githubusercontent.com/assets/20582179/19161343/093b674a-8bb9-11e6-8491-e3efba31b031.png)
