### ISSUE TITLE
Branding for Main Site

### ISSUE THREAD

**Issue by darinduvall** [IBM-Bluemix/insurance-bot#92]

**Comment by kingtraceyj** [comment]
@colbycheeze @rvennam @uwefassnacht @Austinauth 

here's a first pass at the web page redesign

feedback welcome! i probably won't be able to make changes until i get back.

here's the icon folder for images: https://ibm.box.com/s/7r6h92pyhj9o2ygsx26wash6fpnv12ls

![chatbot_webpage](https://cloud.githubusercontent.com/assets/20582179/19163961/b41797ce-8bc3-11e6-8d20-90cf6c76b3d5.png)

**Comment by rvennam** [comment]
Love it. My only feedback...highlight the bot feature a bit more
