### ISSUE TITLE
UI Design - Customer Mobile App Demo Pages

### ISSUE THREAD

**Issue by Austinauth** [IBM-Bluemix/insurance-bot#93]
Both UX and Visual passes are needed.
## Required Pages
- **User Login Page:** User should be able to quickly login to the demo.
- **Landing Page:** Insurance categories are immediately available. Emulating real existing insurance pages, the user should be able to invoke chat straight from the landing page. No need to dive into a category first. Long-term we can spend more time fleshing out this page.
- **Chat Bot Page:** User should be able to chat freely with the chat bot. User should be able to easily navigate back to their point-of-origin (landing page). 
#### Landing Page

![box-image](https://cloud.githubusercontent.com/assets/6994218/19051751/b35a417a-8979-11e6-838d-80dd1064e7df.png)
#### Health Page (Is this needed?)

![box-image-1](https://cloud.githubusercontent.com/assets/6994218/19051780/d683886e-8979-11e6-9e07-606187851699.png)
#### Chat Bot

![box-image-2](https://cloud.githubusercontent.com/assets/6994218/19051809/e6b2ae4a-8979-11e6-8f8b-16846141ca5c.png)

**Comment by Austinauth** [comment]
@kingtraceyj @darinduvall @colbycheeze @rvennam @antonmc 

## Mobile App UX Wireframe Concepts

Below are some UX concepts of the mobile app portion of the insurance bot scenario.

## Login Screen

![v1-mobile_login](https://cloud.githubusercontent.com/assets/6994218/19086764/0f67c076-8a35-11e6-809f-b9462fb7364d.png)

**Items to Highlight:**
- Basic login screen
- Room for branding
- Secondary options like forgotten password & sign-up
- One-time login 

## Mobile Dashboard Default

![v1-mobile_home](https://cloud.githubusercontent.com/assets/6994218/19086839/6a728078-8a35-11e6-8f5c-36707e9daffb.png)

**Items to Highlight:**
- Profile section makes scenario seem personal and real
- Placeholder settings icon
- Simple and clear hierarchy of choices
- Clear call to action for concierge
- User should not be required to dive into a category to initiate a chat

**Open Questions:**
- What term are we using for the chat bot? Concierge?
- Are there other items we can include on this page to make it seem more real?
- What should our call-to-action be for initiating a chat?

## Chat Bot

![v1-mobile_chat](https://cloud.githubusercontent.com/assets/6994218/19086997/0dabc0b0-8a36-11e6-9881-ba3e666dcba9.png)

**Items to Highlight:**
- Common chat pattern
- Option to return to home
- Watson branding can be replaced with insurance company branding

**Open Questions:**
- Should chat offer/support actionable items (see below)
  ![screen shot 2016-10-04 at 1 27 24 pm](https://cloud.githubusercontent.com/assets/6994218/19087064/52d4fc2e-8a36-11e6-8601-2d43f4773e47.png)

## Mobile Dashboard Chat Initiated

![v2-mobile_home-existing-chat-alert](https://cloud.githubusercontent.com/assets/6994218/19087113/79c7a9bc-8a36-11e6-8bfd-e80a468e260a.png)

**Items to Highlight:**
- Chat icon module on the bottom right provides the user with a way to return to an open chat if they've returned to the dashboard. It also provides a way to indicate to the user when a response has been made.

<hr>

## Potential Variations

### Dashboard Variation

![v2-mobile_home](https://cloud.githubusercontent.com/assets/6994218/19087359/51c2c75c-8a37-11e6-8426-09107e675e3d.png)

### Mobile Dashboard Chat Initiated Variation

![v2-mobile_home-existing-chat-alert](https://cloud.githubusercontent.com/assets/6994218/19087354/4d70b6e6-8a37-11e6-9cfc-8940005b825d.png)

**Comment by colbycheeze** [comment]
does it have to say Concierge? I don't think that would make sense to most people.
Maybe something like, "Ask a question" or...I don't know we could brainstorm.

**Comment by Austinauth** [comment]
@colbycheeze 

> does it have to say Concierge? I don't think that would make sense to most people.
> Maybe something like, "Ask a question" or...I don't know we could brainstorm.

Agreed. Something like "Ask a Question" seems a lot clearer.

**Comment by kingtraceyj** [comment]
### hi-fi comps

our goal is to keep everything legible and clean since it will presented in a large room.

log-in:
keeping it pretty simple right now. the logo is coming soon so we can choose to put that here or choose to do a background imageor leave it.

![1_insurancebot_login](https://cloud.githubusercontent.com/assets/20582179/19121262/6a3f8bee-8aeb-11e6-86c8-867d9f275d40.png)

home screen:
![2_insurancebot_home](https://cloud.githubusercontent.com/assets/20582179/19121271/71eac5e8-8aeb-11e6-8e66-8d82aa9205dd.png)

chat:
we decided to go with a speech bubble like a text message to help differentiate the two chatters.

![3_insurancebot_chat](https://cloud.githubusercontent.com/assets/20582179/19121278/789e772c-8aeb-11e6-9409-6c49e120207e.png)

for the ana avatar do we want to go with watson branding or a robot illustration?

**Comment by sharpstef** [comment]
Since I expect looking in here will turn into combing through comments, we may need to move comments specific to the dialog to another thread. Dialog isn't to be generated by the mobile app but by the service itself.

**Comment by antonmc** [comment]
Hi - I made an invision preview ...

https://projects.invisionapp.com/share/D28UEG7FY#/screens

You can click the buttons to get a feel for how this plays

if you turn comment mode on you'll see some comments but I'll write more here ...

**Comment by Austinauth** [comment]
@antonmc Thank you for making the Invision prototype!

@kingtraceyj and I are going through the feedback together. Responses below reflect both of our opinions.

<hr>

Comments in response to invision prototype: https://projects.invisionapp.com/share/D28UEG7FY#/screens

## General Feedback

> On contrast issues.

Contrast as been tested for accessibility. We will project comps on various monitors and sizes and adjust accordingly.

## Home Screen Feedback

> (Home Screen // Comment 3) We don't currently have a way in our demo to upload photos. I don't want to make this a hard coded demo.
> 
> We'll either have to implement a way to add photos to accounts, handle when they don't have one, or hand manage the database to include one.

Lets try to make photos happen. First and foremost this is a demo that will be shown to many people on stage.

Avatar images are very useful for the demo presentation. Not only do they assist in identifying who is speaking at any give time, but they help the audience build empathy for the user going through the scenario. @rvennam and @colbycheeze both agree with this sentiment. 

> (Home Screen // Comment 4) We don't have ids in the demo version of the site yet either - see comments for photo.

Placeholder/dummy content to make the scenario seem more real. We can remove this if it is a big issue.

> On settings icon (Home Screen // Comment 2): What is the interaction model behind this? Where does it lead? Is it necessary?

This is a placeholder icon to make the app seem real. This is an on-stage demo and a happy path. We will be including some placeholder/dummy content to make the presentation seem real. @rvennam and @colbycheeze both agree with this sentiment. If absolutely necessary we can remove these items in the future.

> On chat icon (Home Screen // Comment 1): What is the navigation model behind this? does this lead to the same place as 'ask a question'? I don't think this fits with iOS interaction convention.

@kingtraceyj: it does lead to the same place as ask a question. it is a little different than most apps but some apps, like snapchat, do have chat on the left. i'll go ahead and remove it and stick to austin's original wireframes.

## Chat Screen

> (Chat Screen // Comment 1) I think this breaks with iOS convention a bit - it's too fiddly in any case - let's not do this.

Can you elaborate on what you mean by fiddly? From what we have seen this is a common IOS pattern (see below).

![screen shot 2016-10-05 at 2 04 21 pm](https://cloud.githubusercontent.com/assets/6994218/19127470/bcde5344-8b04-11e6-8c2c-dd18cb1f91c6.png)

![screen shot 2016-10-05 at 2 04 57 pm](https://cloud.githubusercontent.com/assets/6994218/19127477/c7b19e52-8b04-11e6-8149-b3ece0bd4731.png)

> (Chat Screen // Comment 4) Where does this take us?

Back to the home screen. We should move this to the left side.

> (Chat Screen // Comment 3) so - as a matter of urgency, we need to see the framework we're using for chatting ... for one thing the keyboard needs to be on here so we understand the ux around typing and sending - we likely won't have a lot of say about how that looks/behaves.

We can default to standard IoS icons if needed.

**Comment by antonmc** [comment]
I'm really unhappy about any disposable demo content.

**Comment by antonmc** [comment]
to the point where I should probably step out and leave you to it

**Comment by rvennam** [comment]
I see it as a placeholder, not disposable content. As we continue to build this out, these are all features that are realistic and possible to implement.

**Comment by antonmc** [comment]
This iPhone app, I'll be honest is not what I had in mind - and I don't know what to do about that right now.

What I had in mind was an iPhone app dedicated to the health insurance - with views for policy, claim history and chat - and to build on that for the future. I know the CloudCo site has more services, but I wanted to concentrate on the insurance service.

In general now, I want to think about Cloud Co's fictional mission. I didn't give as deep thought to the concept as it probably needed. Not many insurance companies have the breadth of services it offers. My health benefits don't also offer car insurance.

**Comment by antonmc** [comment]
I'm not part of the demo. I should step aside. 

I do have to think of the future of the app and probably will not go this direction.

**Comment by Austinauth** [comment]
@antonmc I think most of us agree with your overall sentiment. I understand the frustration around wanting to make the sample app as close to _real_ as possible.

Right now we are purely focused on telling the best story we can via the demo presentation. In the future we would love to help make the sample app as robust and near to your vision as possible. Its just not in scope for what we are trying to accomplish for the World of Watson demo.

**Comment by l2fprod** [comment]
about 

> We'll either have to implement a way to add photos to accounts, handle when they don't have one, or hand manage the database to include one.
> Lets try to make photos happen. First and foremost this is a demo that will be shown to many people on stage.

A simple way to handle photos is to grab the gravatar from the email address:
https://en.gravatar.com/support/what-is-gravatar/

No need to handle any uploads in our app. Just create a gravatar, register your email. Then in our code, pick the image from gravatar for the email address of the user account.

**Comment by kingtraceyj** [comment]
updated hi-fis for mobile

![1_insurancebot_login](https://cloud.githubusercontent.com/assets/20582179/19163168/9455e8bc-8bc0-11e6-8e37-78a17d9c8b39.png)
![2_insurancebot_homescreen](https://cloud.githubusercontent.com/assets/20582179/19163169/94577ff6-8bc0-11e6-8f09-d77906166cab.png)
![3_insurancebot_chat](https://cloud.githubusercontent.com/assets/20582179/19163170/945b4640-8bc0-11e6-820a-80a7c32280c9.png)

**Comment by l2fprod** [comment]
@Austinauth @kingtraceyj we can close that one right? We have enough of the design for our first public target.

**Comment by rvennam** [comment]
@VidyasagarMSC
