### ISSUE TITLE
UI Design - Admin Desktop Dashboard

### ISSUE THREAD

**Issue by Austinauth** [IBM-Bluemix/insurance-bot#94]
UX and Visual passes are needed.
## Required Pages

**Admin Dashboard:** From the admin dashboard user should be able to view and interact with various user chats. User should be able to immediately identify chat sentiment and be alerted to any changes in sentiment that cross a certain threshold (negative/positive). 

User should also be alerted when specific Watson training is available and is provided a way to quickly navigate to the Watson tool. Finally, user should be able to see and potentially interact with placeholder analytics and layout content.

**Comment by Austinauth** [comment]
@kingtraceyj @darinduvall @colbycheeze @rvennam @antonmc @uwefassnacht 

Following up on the mobile concepts posted yesterday, here is the first pass at the Admin Panel Design.

# Admin Panel UX Wireframe Concept

![admin-panel](https://cloud.githubusercontent.com/assets/6994218/19121365/d645d69a-8aeb-11e6-901b-2d9ee60d1329.png)

**Items to Highlight:**
- User can toggle between active chats by selecting a chat from the _Active Chats_ list
- Active chat list conveys user sentiment at a glance
- Current Sentiment, Sentiment Breakdown and Conversation time are all captured for the selected chat log
- Conversation log captures and conveys the conversation as it develops. Individual comment sentiment is clearly conveyed through iconography and color

**Questions/Comments:**
- Verbiage and diagrams to be finessed
- Are there any other items we want to convey here?
- Additional screens for the alert portion of the scenario will be provided

**Comment by kingtraceyj** [comment]
hi-fi comps of dashboard
@uwefassnacht this is an example of what a full dashboard with alerts and graphs would look like. 
![chatbot_admindashboard](https://cloud.githubusercontent.com/assets/20582179/19162732/b073fa7c-8bbe-11e6-8c1a-68436ec1d3fd.png)

@Austinauth and I had a few questions:

Inline Chat Training Notification: 
- Can we link directly to the Conversation tool?
- Can we surface the actual node/entity in Conversation where the error occurs?
- Is this the appropriate notification copy?

Global Notifications
- Do we need a global notification pattern to indicate when Conversation needs training or will the inline chat notification suffice?

**Comment by l2fprod** [comment]
@Austinauth @kingtraceyj can this be closed? For WoW target the design looks locked down.
